// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3rAU691_Z3bkWU5m1uLZVHM7Myn0DVio',
    appId: '1:1083886254890:web:3f73bfacfedbe58d047c53',
    messagingSenderId: '1083886254890',
    projectId: 'flutter-notes-app-46f70',
    authDomain: 'flutter-notes-app-46f70.firebaseapp.com',
    storageBucket: 'flutter-notes-app-46f70.appspot.com',
    measurementId: 'G-PZ1TXGBVQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPnNIovpYYiRwGuFn4GH1NlLGx0t9Le6A',
    appId: '1:1083886254890:android:3a33601514ac03c1047c53',
    messagingSenderId: '1083886254890',
    projectId: 'flutter-notes-app-46f70',
    storageBucket: 'flutter-notes-app-46f70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX0bxP3ZeAUo6MhcGmIQM3AK74X91qUuM',
    appId: '1:1083886254890:ios:be89234989ce547d047c53',
    messagingSenderId: '1083886254890',
    projectId: 'flutter-notes-app-46f70',
    storageBucket: 'flutter-notes-app-46f70.appspot.com',
    iosClientId: '1083886254890-p332206pnlp8ekq5fqkcuifiuhq8gpt4.apps.googleusercontent.com',
    iosBundleId: 'com.nodejscleanarch.flutter',
  );
}
